apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: Nodeport
  selector:
   app: nginx
  ports:
  - name: svx-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30008
    
